//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record1
    {
        public int id { get; set; }
        public int Serviceid { get; set; }
        public int Clientid { get; set; }
        public int Materialsid { get; set; }
        public int Barberid { get; set; }
        public System.DateTime DataAndTime { get; set; }
        public string Comment { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Client Client { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Service Service { get; set; }
    }
}
